version: "3"

services:
  
  http:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - "sock:/sock"
      - "./config/nginx:/etc/nginx/conf.d:z"

    labels:
      # the "sock" volume will need to be shared to the same pod, so let's
      # declare that this is not a PVC
      katenary.io/empty-dirs: sock

      # use ./config/nginx as a configMap
      katenary.io/configmap-volumes: ./config/nginx

      # declare an ingress
      katenary.io/ingress: 80

  php:
    image: php:fpm
    volumes:
      - "sock:/sock"
      - "./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:z"
    labels:
      # fpm will need to use a unix socket shared
      # with nginx (http service above), so we want here
      # make a single pod containing nginx and php
      katenary.io/same-pod: http
      # use the ./config/php files as a configMap
      katenary.io/configmap-volumes: ./config/php/www.conf

volumes:
  sock:
