# markdownlint configuration file
default: true

MD013: # Line length
  line_length: 120

MD010: # Hard tabs
  code_blocks: false

# no inline HTML
MD033: false

# heading as first line element...
MD041: false

# list indentation
MD007:
  indent: 4

# no problem using several code blocks styles
MD046: false
