apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-blog'
  labels:
    katenary.io/component: blog
    katenary.io/project: ghost
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 0c2bbf548ff569c3dc5d77dc158e98bbe86fb5d4
    katenary.io/version: master
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: blog
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: blog
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: blog
          image: '{{ .Values.blog.image }}'
          ports:
            - name: blog
              containerPort: 2368
          env:
            - name: url
              value: http://{{ .Values.blog.ingress.host }}

