apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-blog'
  labels:
    katenary.io/component: blog
    katenary.io/project: ghost
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 0c2bbf548ff569c3dc5d77dc158e98bbe86fb5d4
    katenary.io/version: master
spec:
  selector:
    katenary.io/component: blog
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 2368
      targetPort: 2368
