apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-database'
  labels:
    katenary.io/component: database
    katenary.io/project: basic
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: b9f12bb7d1e97901c1d7680394209525763f6640
    katenary.io/version: master-3619cc4
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: database
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: database
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: database
          image: '{{ .Values.database.image }}'
          ports:
            - name: database
              containerPort: 3306
          env:
            - name: MARIADB_PASSWORD
              value: foo
            - name: MARIADB_DATABASE
              value: myapp
            - name: MARIADB_ROOT_PASSWORD
              value: foobar
            - name: MARIADB_USER
              value: foo

