apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-webapp'
  labels:
    katenary.io/component: webapp
    katenary.io/project: basic
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: b9f12bb7d1e97901c1d7680394209525763f6640
    katenary.io/version: master-3619cc4
spec:
  selector:
    katenary.io/component: webapp
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
