{{- if .Values.http.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}-http'
  labels:
    katenary.io/component: http
    katenary.io/project: same-pod
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 74e67695bfdbb829f15531321e158808018280e0
    katenary.io/version: master-bf44d44
spec:
  {{- if and .Values.http.ingress.class (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: '{{ .Values.http.ingress.class }}'
  {{- end }}
  rules:
    - host: '{{ .Values.http.ingress.host }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: '{{ .Release.Name }}-http'
                port:
                  number: 80
              {{- else }}
              serviceName: '{{ .Release.Name }}-http'
              servicePort: 80
              {{- end }}

{{- end -}}
