apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-http'
  labels:
    katenary.io/component: http
    katenary.io/project: same-pod
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 74e67695bfdbb829f15531321e158808018280e0
    katenary.io/version: master-bf44d44
spec:
  selector:
    katenary.io/component: http
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
