site_name: Katenary documentation
docs_dir: ./docs
plugins:
  - search
  - inline-svg
  - manpage:
      enabled: true
      preprocess: preprocess.py
      pages:
        - title: Katenary
          header: Katenary helm chart generator
          output: share/man/man1/katenary.1
          inputs:
            - usage.md
            - labels.md
theme:
  name: material
  custom_dir: overrides
  logo: statics/logo-bright.svg
  favicon: statics/icon.svg
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - statics/main.css
extra_javascript:
  - statics/addons.js
copyright: Copyright &copy; 2021 - 2024 - Katenary authors
extra:
  generator: false
  social:
    - icon: fontawesome/brands/git
      link: https://repo.katenary.io/katenary/katenary
nav:
  - "Home": index.md
  - usage.md
  - labels.md
  - Behind the scene:
      - coding.md
      - dependencies.md
  - FAQ: faq.md
  - Go Packages:
      - packages/cmd/katenary.md
      - packages/internal/parser.md
      - packages/internal/utils.md
      - Generator:
          - Index: packages/internal/generator.md
          - ExtraFiles: packages/internal/generator/extrafiles.md
          - labels:
              - packages/internal/generator/labels.md
              - Labelstructs: packages/internal/generator/labels/labelstructs.md
          - KatenaryFile: packages/internal/generator/katenaryfile.md
