site_name: Katenary documentation
docs_dir: ./docs
theme:
  name: material
  custom_dir: overrides
  logo: statics/logo.png
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: false
  - pymdownx.superfences
extra_css:
  - statics/main.css
extra_javascript:
  - statics/addons.js
copyright: Copyright &copy; 2021 - 2022 - Katenary authors
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/metal3d/katenary
nav:
  - "Home": index.md
  - usage.md
  - labels.md
