site_name: Katenary documentation
docs_dir: ./docs
plugins: 
  - search
  - inline-svg
theme:
  name: material
  custom_dir: overrides
  logo: statics/logo-bright.svg
  favicon: statics/icon.svg
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: false
  - pymdownx.superfences
extra_css:
  - statics/main.css
extra_javascript:
  - statics/addons.js
copyright: Copyright &copy; 2021 - 2024 - Katenary authors
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/metal3d/katenary
nav:
  - "Home": index.md
  - usage.md
  - labels.md
  - Behind the scene:
    - coding.md
    - dependencies.md
  - FAQ: faq.md
  - Go Packages:
    - packages/cmd/katenary.md
    - packages/generator.md
    - packages/parser.md
    - packages/update.md
    - packages/utils.md
    - packages/generator/extrafiles.md
