ARG GOVERSION=1.24

FROM docker.io/golang:${GOVERSION} AS builder
WORKDIR /go/src/github.com/katenary/katenary
COPY . .
ARG VERSION=master
RUN set -xe; \
  CGO_ENABLED=0 go build -ldflags="-X 'github.com/katenary/katenary/internal/generator.Version=$VERSION'" -trimpath -o katenary ./cmd/katenary

FROM scratch
LABEL org.opencontainers.image.source=https://github.com/katenary/katenary
LABEL org.opencontainers.image.description="Katenary converts compose files to Helm Chart"
LABEL org.opencontainers.image.licenses=MIT
COPY --from=builder /go/src/github.com/katenary/katenary/katenary /katenary
VOLUME /project
WORKDIR /project
ENTRYPOINT ["/katenary"]
