name: Go-Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - develop
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: tests-results
          path: |
            coverprofile.out
            gotest.json
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Launch Test
        run: |
          go vet ./... && go test -coverprofile=coverprofile.out -json -v ./... > gotest.json
  sonar:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tests-results
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
