name: Set README on GitHub

# Trigger this workflow every 12 hours.
on:
  push:
    branches:
      - "**"

jobs:
  rewrite_readme:
    name: Append header on README
    runs-on: ubuntu-latest
    if: contains(github.server_url, 'github.com')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Write header
        run: |
          cp README.md __OLD.md

          cat 1> README.md <<-EOF
          > **⚠️ Project has moved !⚠️**
          >
          > **Project moved to https://repo.katenary.io/katenary/katenary**
          >
          > Please, update your bookmaks. Discussion about the move is here : https://github.com/orgs/Katenary/discussions/162
          EOF

          cat __OLD.md >> README.md
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: README.md
          message: "Add mirror information"
          push: true
