# Thanks to blender authors to provide this.
# Adaptation made for Katenary

name: Close GitHub Pull Requests

# Trigger this workflow every 12 hours.
on:
  schedule:
    - cron: "* */12 * * *"

jobs:
  close_prs:
    name: Close Pull Requests
    runs-on: ubuntu-latest
    if: contains(github.server_url, 'github.com')
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          # Number of days before a pull request is marked as stale.
          days-before-pr-stale: 0
          # Number of days before a pull request is closed.
          days-before-pr-close: 0
          # Message posted when closing a pull request.
          stale-pr-message: |
            This pull request has been automatically closed because this repository is a read-only mirror. 
            Katenary developement happens on [repo.katenary.io](https://repo.katenary.io/Katenary/katenary).
